@startuml
class Order {
   id : Long
   orderTime : LocalDateTime
}

class OrderPosition {
    id : Long
    quantity: int
}

class Article {
    id: Long
    number: String
    name : String
    price : Number
}

class Customer {
    id : Long
    firstname : String
    lastname : String
    creationDate : LocalDate
    changeDate : LocalDateTime
    type : CustomerType
    readDate : LocalDateTime
}

Customer "1" -up-> "0..*" Order : \t\t
Order "1" -right-> "1..*" OrderPosition : \t\t
OrderPosition "0..*" -right-> "1" Article : \t\t
@enduml